config/routes.rb
Rails.application.routes.draw do
  resources :todos
  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
# == Schema Information
#
# Table name: todos
#
#  id         :bigint           not null, primary key
#  session_id :string           not null
#  title      :string           not null
#  completed  :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Todo < ApplicationRecord
  validates :session_id, presence: true
  validates :title, presence: true

  scope :completed, -> { where completed: true }
  scope :active, -> { where completed: false }

  def active?
    !completed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_filter, only: [:index]
  before_action :set_todo, only: [:update, :destroy]

  def index
    @all_todos = Todo.where(session_id: session.id).order(:created_at)
    @filtered_todos = @all_todos.public_send(session[:filter])
  end

  def create
    Todo.create todos_params
    redirect_to todos_path
  end

  def update
    @todo&.update todos_params
    redirect_to todos_path
  end

  def destroy
    @todo&.destroy
    redirect_to todos_path
  end

  private

  def todos_params
    params.require(:todo).permit(:title, :completed).merge(session_id: session.id)
  end

  def set_todo
    @todo = Todo.find_by(session_id: session.id, id: params[:id])
  end

  def set_filter
    session[:filter] = params[:filter] || session[:filter] || "all"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimulusTodomvc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_actions.html.erb
<section class="footer">
  <span class="todo-count">
    <strong><%= @all_todos.active.count %></strong> <%= "item".pluralize @all_todos.active.count %> left
  </span>

  <ul class="filters">
    <% %w[all active completed].each do |filter| %>
      <li>
        <%= link_to filter.titleize, todos_path(filter: filter), class: ("selected" if params[:filter] == filter) %>
      </li>
    <% end %>
  </ul>

  <% if @all_todos.completed.any? %>
    <button class="clear-completed" data-controller="todos" data-action="click->todos#destroyCompleted">
      Clear completed
    </button>
  <% end %>
</section>

app/views/todos/_badges.html.erb
<div style="position:relative; top:-10px; left:10px;">
  <iframe src="https://ghbtns.com/github-btn.html?user=hopsoft&repo=stimulus_todomvc&type=star&count=true" frameborder="0" scrolling="0" style="height:20px;"></iframe>
  <iframe src="https://ghbtns.com/github-btn.html?user=hopsoft&repo=stimulus_todomvc&type=fork&count=true" frameborder="0" scrolling="0" style="height:20px;"></iframe>
  <iframe src="https://ghbtns.com/github-btn.html?user=hopsoft&type=follow&count=true" frameborder="0" scrolling="0" style="height:20px;"></iframe>
  <iframe src="https://ghbtns.com/github-btn.html?user=andrewmcodes&type=follow&count=true" frameborder="0" scrolling="0" style="height:20px;"></iframe>
</div>

app/views/todos/_form.html.erb
<%= form_for Todo.new, remote: true do |f| %>
  <%= f.text_field :title, class: "new-todo", placeholder: "What needs to be done?", autofocus: true %>
<% end %>

app/views/todos/_todo.html.erb
<% if todo.id == @edit_id %>
  <li class="editing">
    <input autofocus type="text" class="edit" value="<%= todo.title %>" <%= "checked" if todo.completed? %>
      data-controller="todos" data-action="change->todos#update keypress->todos#cancelEdit blur->todos#cancelEdit" data-id="<%= todo.id %>">
  </li>
<% else %>
  <li class="<%= "completed" if todo.completed? %>" data-controller="todo">
    <div class="view">
      <%= form_for todo, remote: true, html: { data: { target: "todo.form" }} do |f| %>
        <%= f.hidden_field :id %>
        <%= f.check_box :completed, class: "toggle", data: { action: "change->todo#submit" } %>
      <% end %>
      <label data-action="click->todos#edit">
        <%= todo.title %>
      </label>
      <%= button_to "&times;".html_safe, todo_path(todo), type: "button", class: "destroy", remote: true, method: :delete %>
    </div>
  </li>
<% end %>

app/views/todos/index.html.erb
<section class="todoapp">
  <header class="header">
    <h1>todos</h1>
    <%= render "todos/form" %>
  </header>

  <% if @all_todos.any? %>
    <section class="main">
      <input class="toggle-all" type="checkbox">
      <label data-controller="todos" data-action="click->todos#toggleAll">
        Mark all as complete
      </label>
      <ul class="todo-list">
        <%= render partial: "todo", collection: @filtered_todos %>
      </ul>
    </section>
  <% end %>

  <%= render "/todos/actions" if @all_todos.any? %>
</section>

<%= render "/todos/badges" %>